<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload1279a632fc20a55730f803284483ed39($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'rapture\\http\\cookie' => '/../src/Cookie.php',
            'rapture\\http\\definition\\httpexceptioninterface' => '/../src/Definition/HttpExceptionInterface.php',
            'rapture\\http\\definition\\httpclientinterface' => '/../src/Definition/HttpClientInterface.php',
            'rapture\\http\\exception\\httpbadrequestexception' => '/../src/Exception/HttpBadRequestException.php',
            'rapture\\http\\exception\\httpforbiddenexception' => '/../src/Exception/HttpForbiddenException.php',
            'rapture\\http\\exception\\httpinternalservererrorexception' => '/../src/Exception/HttpInternalServerErrorException.php',
            'rapture\\http\\exception\\httpmethodnotallowedexception' => '/../src/Exception/HttpMethodNotAllowed.php',
            'rapture\\http\\exception\\httpnotfoundexception' => '/../src/Exception/HttpNotFoundException.php',
            'rapture\\http\\exception\\httpnotimplementedexception' => '/../src/Exception/HttpNotImplementedException.php',
            'rapture\\http\\exception\\httpunauthorizedexception' => '/../src/Exception/HttpUnauthorizedException.php',
            'rapture\\http\\client' => '/../src/Client.php',
            'rapture\\http\\request' => '/../src/Request.php',
            'rapture\\http\\response' => '/../src/Response.php',
            'rapture\\http\\stream' => '/../src/Stream.php',
            'rapture\\http\\uploadedfile' => '/../src/UploadedFile.php',
            'rapture\\http\\uri' => '/../src/Uri.php',
            'psr\http\message\uriinterface' => '/../../../vendor/psr/http-message/src/UriInterface.php',
            'psr\http\message\serverrequestinterface' => '/../../../vendor/psr/http-message/src/ServerRequestInterface.php',
            'psr\http\message\requestinterface' => '/../../../vendor/psr/http-message/src/RequestInterface.php',
            'psr\http\message\responseinterface' => '/../../../vendor/psr/http-message/src/ResponseInterface.php',
            'psr\http\message\streaminterface' => '/../../../vendor/psr/http-message/src/StreamInterface.php',
            'psr\http\message\messageinterface' => '/../../../vendor/psr/http-message/src/MessageInterface.php',
            'psr\http\message\uploadedfileinterface' => '/../../../vendor/psr/http-message/src/UploadedFileInterface.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload1279a632fc20a55730f803284483ed39');
// @codeCoverageIgnoreEnd
